'use client'

import { FormEvent, useState } from 'react'
import Link from 'next/link'
import { ArrowLeft, Check, Download, Heart, LockKeyhole, ShieldCheck } from 'lucide-react'
import { RazorpayCheckout } from '@/components/razorpay-checkout'

export default function DonationPage() {
  const [submitted, setSubmitted] = useState(false)
  const [name, setName] = useState('')
  const [amount, setAmount] = useState('1001')
  const submit = (event: FormEvent) => { event.preventDefault(); setSubmitted(true) }
  const downloadReceipt = () => { const receipt = `NEW PANCHSHEEL KE RAJA\nDonation Receipt\n\nDonor: ${name}\nAmount: ₹${amount}\nDate: ${new Date().toLocaleDateString('en-IN')}\n\nThank you for supporting our seva.`; const blob = new Blob([receipt], { type: 'text/plain' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = 'new-panchsheel-ke-raja-receipt.txt'; a.click(); URL.revokeObjectURL(url) }
  return <main className="donation-page"><div className="donation-nav"><Link href="/" className="back-link"><ArrowLeft size={16}/> Back to home</Link><Link href="/" className="donation-brand"><img src="/logo.png" alt="New Panchsheel Ke Raja logo" className="brand-logo"/><span><strong>NEW PANCHSHEEL</strong><small>KE RAJA · GANESH MANDAL</small></span></Link><span className="secure-label"><LockKeyhole size={14}/> Secure giving</span></div><section className="donation-shell"><div className="donation-intro"><span className="eyebrow">A LITTLE GOES A LONG WAY</span><h1>Support our<br/><em>seva.</em></h1><p>Every offering helps us create a more meaningful Ganeshotsav — and continue the work that matters, long after the lights go down.</p><div className="donation-quote"><Heart size={19}/><span>“Devotion is not only what we feel.<br/><b>It is what we do for one another.”</b></span></div><div className="donation-points"><p><Check size={16}/> Cultural & religious programs</p><p><Check size={16}/> Community seva initiatives</p><p><Check size={16}/> Transparent use of every contribution</p></div></div><div className="donation-card"><div className="donation-card-head"><div><span className="eyebrow">NEW PANCHSHEEL KE RAJA</span><h2>Make an offering</h2></div><ShieldCheck size={25}/></div>{submitted ? <div className="receipt-success"><div className="success-icon"><Check/></div><h3>Thank you, {name || 'Bappa devotee'}.</h3><p>Your offering of <b>₹{amount}</b> is ready for secure checkout.</p><RazorpayCheckout amount={Number(amount)} name={name}/><button className="button button-dark" onClick={downloadReceipt}><Download size={16}/> Download Receipt</button><button className="start-over" onClick={() => setSubmitted(false)}>Edit offering</button></div> : <form onSubmit={submit} className="donation-form"><label>Donor name<input required value={name} onChange={e => setName(e.target.value)} placeholder="Enter your full name"/></label><label>Donation amount<input required min="100" max="5000000" type="number" value={amount} onChange={e => setAmount(e.target.value)} placeholder="Enter amount"/></label><div className="amount-options">{['501','1001','2501','5001'].map(value => <button type="button" key={value} className={amount === value ? 'selected' : ''} onClick={() => setAmount(value)}>₹{value}</button>)}</div><button className="button button-gold donate-submit" type="submit">Continue to payment <span>→</span></button><p className="form-legal"><LockKeyhole size={12}/> You will be redirected to Razorpay&apos;s secure hosted checkout.</p></form>}</div></section><footer className="donation-footer"><span>© 2026 New Panchsheel Ke Raja</span><a href="mailto:hello@newpanchsheelkeraja.org">Contact us</a><Link href="/">Return to website →</Link></footer></main>
}
